all:
  children:
    router:
      hosts:
        ohana
    dns:
      hosts:
        majesty
    database:
      hosts:
        nani
    kubernetes:
      children:
        leader:
          hosts:
            k8s-leader:
              ansible_user: root
        leader-backup:
          hosts:
#            k8s-worker-jetson:
        workers:
          children:
            pis:
              hosts:
                k8s-worker-100:
                  ansible_user: root
                k8s-worker-102:
                  ansible_user: root
            gpus:
              hosts:
                k8s-worker-nv1:
                k8s-worker-nv2:
                k8s-worker-nv3:
            x86:
              hosts:
                experiment626:
                experiment624:
localhost:
