all:
  children:
    cdn:
      hosts:
    rpki:
    database:
      children:
        db-leader:
        db-followers:
          hosts:
    kubernetes:
      children:
        kube-leader-and-backups:
          children:
            kube-leader:
              hosts:
                turo.local.pigscanfly.ca:
            leader-backup:
              hosts:
        workers:
          children:
#            pis:
#              hosts:
#                erpi1.local.pigscanfly.ca:
#                erpi2.local.pigscanfly.ca:
#                erpi3.local.pigscanfly.ca:
#                rpi1.local.pigscanfly.ca:
#                rpi2.local.pigscanfly.ca:
            docker-hosts:
              children:
                gpus:
                  children:
                    arm-gpus:
                      hosts:
#                        nvmini3.local.pigscanfly.ca:
#                        nvmini4.local.pigscanfly.ca:
#                        k8s-worker-nv1.local.pigscanfly.ca:
#                        k8s-worker-nv3.local.pigscanfly.ca:
                    x86-gpus:
                      hosts:
                        plushy.local.pigscanfly.ca:
                        scrump.local.pigscanfly.ca:
                amd-gpus:
                  hosts:
                x86:
                  hosts:
localhost:
