---
# Cleanup old install if desired
- hosts: kubernetes
  tasks:
  - name: Remove k3s install
    ansible.builtin.shell: "k3s-uninstall.sh || k3s-agent-uninstall.sh || echo k"
    become: true
  - name: Remove kubernetes stuff
    file:
      path: "/etc/kubernetes"
      state: absent
    become: true
  - name: Remove root kube config
    file:
      path: "/root/.kube"
      state: absent
    become: true
  - name: Remove root kubeconfig
    file:
      path: "/root/kubeconfig"
      state: absent
    become: true
  - name: Remove rancher
    file:
      path: "/etc/rancher"
      state: absent
    become: true
  - name: Remove k3sup
    file:
      path: "/usr/local/bin/k3sup"
      state: absent
    become: true
  - name: Remove kubelet
    file:
      path: "/var/kubelet"
      state: absent
    become: true
  - name: Remove rancher var
    file:
      path: "/var/rancher"
      state: absent
    become: true
  - name: Remove /var/lib/rancher
    file:
      path: "/var/lib/rancher"
      state: absent
    become: true
  - name: Remove ceph
    file:
      path: "/var/lib/ceph"
      state: "absent"
    become: true
  - name: Remove rook
    file:
      path: "/var/lib/rook"
      state: "absent"
    become: true
#  - name: Zap
#    ansible.builtin.shell: "/zap || echo \"nozap\""
#    become: true
  - name: Cleanup promisc
    file:
      path: "/etc/init.d/make-promisc"
      state: "absent"
    become: true
#  - name: Remove docker, containerd and friends
#    apt:
#      pkg:
#        - docker
#        - docker-engine
#        - docker.io
#        - runc
#        - containerd
#        - docker-ce
#        - docker-ce-cli
#        - containerd.io
#      state: absent
#      purge: yes
#    become: yes
- hosts: kubernetes
  become: true
#  serial: 1
#  roles:
#  - role: GROG.reboot
#    reboot_connect_timeout: 120
#    reboot_interval: yes
#    reboot_interval_seconds: 480
#    reboot_wait_timeout: 900
