---
- hosts: jumba
  become: yes
  tasks:
  - name: Create storage directory
    ansible.builtin.shell: "mkdir -p /primary/plex"
    args:
      creates: "/primary/plex"
  - name: Download plex
    get_url:
      url: "https://downloads.plex.tv/plex-media-server-new/1.22.3.4392-d7c624def/debian/plexmediaserver_1.22.3.4392-d7c624def_amd64.deb"
      dest: "/tmp/plex.deb"
  - name: Install Plex
    apt:
      deb: "/tmp/plex.deb"
  - name: Give plex permission for the plex directory
    ansible.builtin.shell: "chown plex /primary/plex"
