---
- hosts: route-server
  vars_files:
    - frr-shared-vars.yaml
  tasks:
  - name: Install some networking tools
    apt:
      pkg:
        - inetutils-traceroute
        - inetutils-ping
        - axel
        - nmap
        - tshark
        - build-essential
        - git
        - bgpq4
    become: yes
  - name: configure global bgp as AS399306
    include_role:
      name: mrlesmithjr.frr
    vars:
      frr_version: 7.5.1
      frr_logging: file /var/log/frr-log info
      frr_ip_forwarding: false
      frr_ipv6_forwarding: false
      frr_daemons:
        bfdd: false
        bgpd: false
        isisd: false
        ldpd: false
        nhrpd: false
        ospf6d: false
        ospfd: false
        pimd: false
        ripd: false
        ripngd: false
        zebra: true
      frr_bgp:
        asns:
          399306:
            log_neighbor_changes: true
            no_ebgp_requires_policy: true
            other:
              - "bgp bestpath as-path multipath-relax"
              - "no bgp network import-check"
            neighbors:
              23.177.73.1:
                asn: 399306
                other:
                  - "prefix-list AnnounceV4 out"
                  - "prefix-list AcceptMostV4 in"
              "2602:fcb1::1":
                asn: 399306
                other:
                  - "prefix-list AnnounceV4 out"
                af_v6:
                  - "activate"
                  - "prefix-list AnnounceV6 out"
                  - "prefix-list AcceptMostV6 in"
              209.209.73.11:
                asn: 53758
                other:
                  - "prefix-list AnnounceV4 out"
              "2602:fcb1::11":
                asn: 53758
                other:
                  - "prefix-list AnnounceV4 out"
                af_v6:
                  - "activate"
                  - "prefix-list AnnounceV6 out"
  - name: Configure zebra
    ansible.builtin.lineinfile:
      path: /etc/frr/daemons
      line: zebra_options="  -A 127.0.0.1 --retain --nl-bufsize 9000000012 --v6-rr-semantics"
    become: yes
  - name: Reload the config
    ansible.builtin.shell: /etc/init.d/frr reload
    become: yes
