---
- hosts: router
  tasks:
  - name: configure global bgp as AS399306
    include_role:
      name: mrlesmithjr.frr
    vars:
      frr_ip_forwarding: true
      frr_ipv6_forwarding: true
      frr_daemons:
        bfdd: true
        bgpd: true
        isisd: false
        ldpd: false
        nhrpd: false
        ospf6d: false
        ospfd: false
        pimd: false
        ripd: false
        ripngd: false
        zebra: true
      frr_bgp:
        asns:
          399306:
            log_neighbor_changes: true
            no_ebgp_requires_policy: true
        redistribute:
          - bgp
          - connected
          - kernel
          - ospf
          - static
        redistribute_v6:
          - bgp
          - connected
          - kernel
