---
- hosts: all
  tasks:
  - name: Add the user 'holden' with a bash shell, appending the group 'sudo'
    ansible.builtin.user:
      name: holden
      shell: /bin/bash
      groups: sudo
      append: yes
  - name: create user private keys if not present
    ansible.builtin.shell: "mkdir ~/.ssh; ssh-keygen  -N '' -f ~/.ssh/id_rsa"
    args:
      creates: "~/.ssh/id_rsa"
  - name: create root private keys if not present
    ansible.builtin.shell: "mkdir ~/.ssh; ssh-keygen  -N '' -f ~/.ssh/id_rsa"
    args:
      creates: "/root/.ssh/id_rsa"
    become: true
  - name: pull keys from github
    uri:
      url: https://github.com/holdenk.keys
      return_content: True
    register: keys
    failed_when: "'ssh-rsa' not in keys.content"
  - name: Configure SSH access
    authorized_key:
      user: holden
      state: present
      key: "{{ keys.content }}"
  - name: Configure root SSH access
    authorized_key:
      user: root
      state: present
      key: "{{ keys.content }}"
    become: true
  - name: Make everyone have a public key
    ansible.builtin.shell: "mkdir -p /root/.ssh; (ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub)"
    args:
      creates: "/root/.ssh/id_rsa.pub"
    become: true

  # Reflexive root access (I know :/ needed for k3sup)
  - name: Fetch the keyfile from the node to master
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
      flat: yes
    become: yes

  - name: Copy the key add to authorized_keys using Ansible module
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
    with_items: 
      - "{{ groups['kubernetes'] }}"
    become: yes
  # Root password login (ugh) cloud.net req
  - name: Set root pw
    ansible.builtin.user:
      name: root
      password: "{{ root_pw | password_hash('sha512') }}"
    become: yes
  - name: Make sure group wheel is not in the sudoers configuration
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      regexp: '^PermitRootLogin no'
    become: yes
  - name: Make sure group wheel is not in the sudoers configuration
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      state: absent
      regexp: '^PasswordAuthentication no'
    become: yes
  - name: Change ssh config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: "PasswordAuthentication yes"
    become: yes
  - name: Change ssh config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: "PermitRootLogin yes"
    become: yes
  - name: Restart ssh
    ansible.builtin.shell: "systemctl restart sshd"
    become: yes

